(define (savegame slot)
  (define out (open-output-file (string-append "savegames/slot" (number->string slot) ".txt") `replace))
  (write (append (list board) (list player (if (equal? `1-player mode) 1 2) name1 name2)) out)
  (close-output-port out)
  (add-to-slot0 slot))

(define (loadgame slot)
  (define f (open-input-file (string-append "savegames/slot" (number->string slot) ".txt")))
  (define inp (read-honu f))
  
  
  (define (maker badlst)
    (if (null? badlst) '()
        (append (list (cdar badlst)) (maker (cdr badlst)))))
  
  (define (do-more-good brd)
    (if (null? brd) '()
        (append (list (do-good (car brd))) (do-more-good (cdr brd)))))
    
    
  (define (do-good lst)
     (if (null? lst) '()
        (if (= 1 (length (car lst))) (append (list '()) (do-good (cdr lst)))
            (append (list (cons (list-ref (car lst) 1) (list-ref (car lst) 3))) (do-good (cdr lst))))))
  
  (set! name1 (caddr (cddr inp)))
  (set! name2 (cadddr (cddr inp)))
  (set! player (caddr inp))
  (set! mode (if (= 1 (cadddr inp)) `1-player `2-player))
  (set! board (do-more-good (maker (cdadr inp))))
  (count-deads-frm-brd board)
  (close-input-port f))


(define (is-present lst item)
  (if (null? lst) #f
      (if (equal? (car lst) item) #t
          (is-present (cdr lst) item))))

(define (add-to-slot0 new-slot)
  (define f (open-input-file "savegames/slot0.txt"))
  (define inp (cdr (read-honu f)))
  (close-input-port f)
  
  (set! inp (remove-duplicates (sort (append inp (list new-slot)) (lambda (x y) (< x y)))))
  
  (define out (open-output-file "savegames/slot0.txt" 'replace))
  (write inp out)
  (close-output-port out))

(define (remove-frm-slot0 slot)
  (define f (open-input-file "savegames/slot0.txt"))
  (define inp (cdr (read-honu f)))
  (close-input-port f)
  (define (rfs-helper)
    (set! inp (foldr (lambda (x y) (if (equal? x slot) y
                                       (append (list x) y)))
                     '()
                     inp))
    (define out (open-output-file "savegames/slot0.txt" 'replace))
    (write inp out)
    (close-output-port out))
  (rfs-helper))


(define (save-win)
  (define load-img-center (make-object img-center%))
  
  ((draw-pixmap my-window) "savegames/save.jpg" (make-posn 0 0) (make-rgb 0 0 0))
  (define game1 (make-object image-button% "savegames/game1.png" 150 100 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 1))) load-img-center))
  (define game2 (make-object image-button% "savegames/game2.png" 150 150 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 2))) load-img-center))
  (define game3 (make-object image-button% "savegames/game3.png" 150 200 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 3))) load-img-center))
  (define game4 (make-object image-button% "savegames/game4.png" 150 250 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 4))) load-img-center))
  (define game5 (make-object image-button% "savegames/game5.png" 150 300 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 5))) load-img-center))
  (define game6 (make-object image-button% "savegames/game6.png" 150 350 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 6))) load-img-center))
  (define game7 (make-object image-button% "savegames/game7.png" 150 400 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 7))) load-img-center))
  (define game8 (make-object image-button% "savegames/game8.png" 150 450 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 8))) load-img-center))
  (define game9 (make-object image-button% "savegames/game9.png"  685 100 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 9))) load-img-center))
  (define game10 (make-object image-button% "savegames/game10.png" 685 150 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 10))) load-img-center))
  (define game11 (make-object image-button% "savegames/game11.png" 685 200 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 11))) load-img-center))
  (define game12 (make-object image-button% "savegames/game12.png" 685 250 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 12))) load-img-center))
  (define game13 (make-object image-button% "savegames/game13.png" 685 300 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 13))) load-img-center))
  (define game14 (make-object image-button% "savegames/game14.png" 685 350 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 14))) load-img-center))
  (define game15 (make-object image-button% "savegames/game15.png" 685 400 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 15))) load-img-center))
  (define game16 (make-object image-button% "savegames/game16.png" 685 450 165 37 (lambda () (begin ((clear-viewport my-window)) (savegame 16))) load-img-center))
  
  (define f (open-input-file "savegames/slot0.txt"))
  (define lst (cdr (read-honu f)))
  (close-input-port f)
  
  (send game1 draw)
  (send game2 draw)
  (send game3 draw)
  (send game4 draw)
  (send game5 draw)
  (send game6 draw)
  (send game7 draw)
  (send game8 draw)
  (send game9 draw)
  (send game10 draw)
  (send game11 draw)
  (send game12 draw)
  (send game13 draw)
  (send game14 draw)
  (send game15 draw)
  (send game16 draw)
  
  (begin
    (cond ((is-present lst 1) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 320 105) (make-rgb 0 0 0))))
    (cond ((is-present lst 2) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 320 155) (make-rgb 0 0 0))))
    (cond ((is-present lst 3) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 320 205) (make-rgb 0 0 0))))
    (cond ((is-present lst 4) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 320 255) (make-rgb 0 0 0))))
    (cond ((is-present lst 5) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 320 305) (make-rgb 0 0 0))))
    (cond ((is-present lst 6) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 320 355) (make-rgb 0 0 0))))
    (cond ((is-present lst 7) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 320 405) (make-rgb 0 0 0))))
    (cond ((is-present lst 8) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 320 455) (make-rgb 0 0 0))))
    (cond ((is-present lst 9) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 855 105) (make-rgb 0 0 0))))
    (cond ((is-present lst 10) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 855 155) (make-rgb 0 0 0))))
    (cond ((is-present lst 11) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 855 205) (make-rgb 0 0 0))))
    (cond ((is-present lst 12) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 855 255) (make-rgb 0 0 0))))
    (cond ((is-present lst 13) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 855 305) (make-rgb 0 0 0))))
    (cond ((is-present lst 14) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 855 355) (make-rgb 0 0 0))))
    (cond ((is-present lst 15) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 855 405) (make-rgb 0 0 0))))
    (cond ((is-present lst 16) ((draw-pixmap my-window) "savegames/overwrite2.png" (make-posn 855 455) (make-rgb 0 0 0)))))
  
  
  (define (mouse-center)
    (define pos (mouse-click-posn (get-mouse-click my-window)))
    (begin
      (send load-img-center search-for-img pos)
      (play)))
  (mouse-center))


(define (load-win)
  (define load-img-center (make-object img-center%))
  
  ((draw-pixmap my-window) "savegames/load.jpg" (make-posn 0 0) (make-rgb 0 0 0))
  (define game1 (make-object image-button% "savegames/game1.png" 150 100 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 1))) load-img-center))
  (define game2 (make-object image-button% "savegames/game2.png" 150 150 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 2))) load-img-center))
  (define game3 (make-object image-button% "savegames/game3.png" 150 200 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 3))) load-img-center))
  (define game4 (make-object image-button% "savegames/game4.png" 150 250 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 4))) load-img-center))
  (define game5 (make-object image-button% "savegames/game5.png" 150 300 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 5))) load-img-center))
  (define game6 (make-object image-button% "savegames/game6.png" 150 350 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 6))) load-img-center))
  (define game7 (make-object image-button% "savegames/game7.png" 150 400 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 7))) load-img-center))
  (define game8 (make-object image-button% "savegames/game8.png" 150 450 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 8))) load-img-center))
  (define game9 (make-object image-button% "savegames/game9.png"  685 100 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 9))) load-img-center))
  (define game10 (make-object image-button% "savegames/game10.png" 685 150 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 10))) load-img-center))
  (define game11 (make-object image-button% "savegames/game11.png" 685 200 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 11))) load-img-center))
  (define game12 (make-object image-button% "savegames/game12.png" 685 250 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 12))) load-img-center))
  (define game13 (make-object image-button% "savegames/game13.png" 685 300 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 13))) load-img-center))
  (define game14 (make-object image-button% "savegames/game14.png" 685 350 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 14))) load-img-center))
  (define game15 (make-object image-button% "savegames/game15.png" 685 400 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 15))) load-img-center))
  (define game16 (make-object image-button% "savegames/game16.png" 685 450 165 37 (lambda () (begin ((clear-viewport my-window)) (loadgame 16))) load-img-center))
  
  
  (define f (open-input-file "savegames/slot0.txt"))
  (define lst (cdr (read-honu f)))
  (close-input-port f)
  (begin
    (cond ((is-present lst 1) (send game1 draw)))
    (cond ((is-present lst 2) (send game2 draw)))
    (cond ((is-present lst 3) (send game3 draw)))
    (cond ((is-present lst 4) (send game4 draw)))
    (cond ((is-present lst 5) (send game5 draw)))
    (cond ((is-present lst 6) (send game6 draw)))
    (cond ((is-present lst 7) (send game7 draw)))
    (cond ((is-present lst 8) (send game8 draw)))
    (cond ((is-present lst 9) (send game9 draw)))
    (cond ((is-present lst 10) (send game10 draw)))
    (cond ((is-present lst 11) (send game11 draw)))
    (cond ((is-present lst 12) (send game12 draw)))
    (cond ((is-present lst 13) (send game13 draw)))
    (cond ((is-present lst 14) (send game14 draw)))
    (cond ((is-present lst 15) (send game15 draw)))
    (cond ((is-present lst 16) (send game16 draw))))
  
  (define (mouse-center)
    (define pos (mouse-click-posn (get-mouse-click my-window)))
    (begin
      (send load-img-center search-for-img pos)
      (play)))
  (mouse-center))